export const collectionList = [
  {
    id: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'sgfde',
    symbol: 'C1',
    redeemable: true,
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/0e2cb94f-94f8-482c-8e78-acb107f829ba.png',
    description: 'New collection',
    dropDate: new Date(),
    generative: false,
    rarities: ['Common', 'Rare', 'Unique'],
    distribution: '',
    traits: [
      {
        type: '1',
        description: 'Hair Color',
        values: ['green', 'red', 'blue'],
      },
      {
        type: '2',
        description: 'Eye Color',
        values: ['green', 'yellow', 'blue'],
      },
    ],
    published: true,
    publishedAt: new Date(),
    smartContractAddress: 'xxx',
    status: 'available',
  },
  {
    id: 2,
    redeemable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'gferrsa',
    symbol: 'C2',
    description: 'New collection 2',
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    dropDate: new Date(),
    generative: false,
    rarities: ['Common', 'Uncommon', 'Rare', 'Unique'],
    distribution: '',
    traits: [
      {
        type: '1',
        description: 'Hair Color',
        values: ['green', 'red', 'blue'],
      },
      {
        type: '2',
        description: 'Age',
        values: ['18', '25', '50'],
      },
    ],
    published: true,
    publishedAt: new Date(),
    smartContractAddress: 'xxx',
    status: 'available',
  },
  {
    id: 3,
    redeemable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'gfqqpo',
    symbol: 'C3',
    description: 'New collection 3',
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    dropDate: new Date(),
    generative: false,
    rarities: ['Common', 'Rare', 'Unique', 'Super unique'],
    distribution: '',
    traits: [
      {
        type: '1',
        description: 'Hair Color',
        values: ['green', 'red', 'blue'],
      },
      {
        type: '2',
        description: 'Weight',
        values: ['10', '15', '20'],
      },
    ],
    published: true,
    publishedAt: new Date(),
    smartContractAddress: 'xxx',
    status: 'available',
  },
  {
    id: 4,
    redeemable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'gfqqpo',
    symbol: 'C3',
    description: 'New collection 3',
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    dropDate: new Date(),
    generative: false,
    rarities: ['Common', 'Rare', 'Unique', 'Super unique'],
    distribution: '',
    traits: [
      {
        type: '1',
        description: 'Hair Color',
        values: ['green', 'red', 'blue'],
      },
      {
        type: '2',
        description: 'Weight',
        values: ['10', '15', '20'],
      },
    ],
    published: true,
    publishedAt: new Date(),
    smartContractAddress: 'xxx',
    status: 'available',
  },
];
