import { IPack } from 'src/common/models/pack';
import { collection } from './collection';

export const packs: IPack[] = [
  {
    id: 1,
    name: 'Test Pack 1',
    price: 100,
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    collection,
    description: 'Lorem ipsum 1',
    createdAt: new Date(),
    updatedAt: new Date(),
    supply: 0,
    quantity: 0,
    availableSupply: 0,
    status: 'draft',
    contentRule: {
      epic: 1,
      legendary: 3,
      rare: 0,
      common: 5,
    },
  },
  {
    id: 2,
    name: 'Test Pack 2',
    price: 200,
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    collection,
    description: 'Lorem ipsum 1',
    createdAt: new Date(),
    updatedAt: new Date(),
    supply: 0,
    quantity: 0,
    availableSupply: 4,
    status: 'draft',
    contentRule: {
      epic: 1,
      legendary: 3,
      rare: 0,
      common: 5,
    },
  },
  {
    id: 3,
    name: 'Test Pack 3',
    price: 300,
    collection,
    description: 'Lorem ipsum 1',
    createdAt: new Date(),
    updatedAt: new Date(),
    supply: 0,
    quantity: 0,
    availableSupply: 2,
    status: 'draft',
    contentRule: {
      epic: 1,
      legendary: 3,
      rare: 0,
      common: 5,
    },
  },
  {
    id: 4,
    name: 'Test Pack 4',
    price: 100,
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    collection,
    description: 'Lorem ipsum 1',
    createdAt: new Date(),
    updatedAt: new Date(),
    supply: 0,
    quantity: 0,
    availableSupply: 1,
    status: 'draft',
    contentRule: {
      epic: 1,
      legendary: 3,
      rare: 0,
      common: 5,
    },
  },
  {
    id: 5,
    name: 'Test Pack 5',
    price: 100,
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    collection,
    description: 'Lorem ipsum 1',
    createdAt: new Date(),
    updatedAt: new Date(),
    supply: 0,
    quantity: 0,
    availableSupply: 2,
    status: 'draft',
    contentRule: {
      epic: 1,
      legendary: 3,
      rare: 0,
      common: 5,
    },
  },
  {
    id: 6,
    name: 'Test Pack 6',
    price: 100,
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    collection,
    description: 'Lorem ipsum 1',
    createdAt: new Date(),
    updatedAt: new Date(),
    supply: 0,
    quantity: 0,
    availableSupply: 1,
    status: 'draft',
    contentRule: {
      epic: 1,
      legendary: 3,
      rare: 0,
      common: 5,
    },
  },
  {
    id: 7,
    name: 'Test Pack 7',
    price: 100,
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    collection,
    description: 'Lorem ipsum 1',
    createdAt: new Date(),
    updatedAt: new Date(),
    supply: 0,
    quantity: 0,
    availableSupply: 0,
    status: 'draft',
    contentRule: {
      epic: 1,
      legendary: 3,
      rare: 0,
      common: 5,
    },
  },
  {
    id: 8,
    name: 'Test Pack 8',
    price: 100,
    imageUrl:
      'https://niftables-dev-collection-bucket.s3.eu-central-1.amazonaws.com/ad263d57-e07f-46dc-8f0d-ca128a11b973.png',
    collection,
    description: 'Lorem ipsum 1',
    createdAt: new Date(),
    updatedAt: new Date(),
    supply: 0,
    quantity: 0,
    availableSupply: 0,
    status: 'draft',
    contentRule: {
      epic: 1,
      legendary: 3,
      rare: 0,
      common: 5,
    },
  },
];
