export const AUTH_REPO = 'AUTH_REPO';
export const USER_REPO = 'USER_REPO';
export const NFT_REPO = 'NFT_REPO';
export const NFT_COLLECTION_REPO = 'NFT_COLLECTION_REPO';
export const PACK_REPO = 'PACK_REPO';
export const NOTIFICATION_REPO = 'NOTIFICATION_REPO';
export const CONFIGURATION_REPO = 'CONFIGURATION_REPO';
